name: morning
on:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: ${{wx630422f6cc51935b.APP_ID }}
      APP_SECRET: ${{ca707786941f55be9b8c07628e4ad307.APP_SECRET }}
      TEMPLATE_ID: ${{8jACUeSDWAQ5-ssEo1buddgINmoPWub-LELVWZzHH2M.TEMPLATE_ID }}
      USER_ID: ${{oX-g16hBQzafqiNPKIw-L3Th7ZKA.USER_ID }}
      START_DATE: ${{ secrets.START_DATE }}
      BIRTHDAY: ${{ secrets.BIRTHDAY }}
      CITY: ${{ secrets.CITY }}
